### ISSUE TITLE
Can't import swiftsimio on certain cosma8 nodes

### ISSUE THREAD

**Issue by JegerBroxterman** [SWIFTSIM/swiftsimio#161]
When importing swiftsimio on some of the cosma8 nodes (cosma8-shm2 or cosma8-shm) the code crashes, see the error massage below:

```
Traceback (most recent call last):
  File "/cosma8/data/dp004/dc-brox1/project1/make_maps/raytracing_slurm.py", line 12, in <module>
    import swiftsimio as sw
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/swiftsimio/_init_.py", line 11, in <module>
    import swiftsimio.visualisation as visualisation
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/swiftsimio/visualisation/_init_.py", line 5, in <module>
    from .projection import scatter, project_gas, project_gas_pixel_grid
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/swiftsimio/visualisation/projection.py", line 28, in <module>
    from swiftsimio.visualisation.projection_backends import backends, backends_parallel
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/swiftsimio/visualisation/projection_backends/_init_.py", line 45, in <module>
    from swiftsimio.visualisation.projection_backends.gpu import scatter as gpu
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/swiftsimio/visualisation/projection_backends/gpu.py", line 68, in <module>
    def scatter_gpu(
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/decorators.py", line 115, in _jit
    disp.compile(argtypes)
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/dispatcher.py", line 794, in compile
    kernel = _Kernel(self.py_func, argtypes, **self.targetoptions)
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/dispatcher.py", line 94, in _init_
    self.cooperative = 'cudaCGGetIntrinsicHandle' in lib.get_asm_str()
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/codegen.py", line 110, in get_asm_str
    return self._join_ptxes(self._get_ptxes(cc=cc))
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/codegen.py", line 148, in _get_ptxes
    ptxes = [nvvm.llvm_to_ptx(irs, **options)]
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/cudadrv/nvvm.py", line 688, in llvm_to_ptx
    return cu.compile(**opts)
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/cudadrv/nvvm.py", line 285, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/cudadrv/nvvm.py", line 303, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/cosma/home/dp004/dc-brox1/.local/lib/python3.9/site-packages/numba/cuda/cudadrv/nvvm.py", line 180, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

IR version 1.6 incompatible with current version 2.0
<unnamed>: error: incompatible IR detected. Possible mix of compiler/IR from different releases.
NVVM_ERROR_IR_VERSION_MISMATCH
```

with 
```
[dc-brox1@login8a ~]$ module list
Currently Loaded Modulefiles:
 1) python/3.9.1-C8   3) armforge/22.0.2   5) gadgetviewer/1.1.3  
 2) cosma/2018        4) hdfview/3.1.4     6) utils/201805  
```

According to Alastair:

> Not a software version problem, but rather a hardware difference - cosma8-shm2 nodes don't have NVIDIA GPUs, and therefore no CUDA.

**Comment by JBorrow** [comment]
what version of numba and llvmlite is being used

**Comment by JBorrow** [comment]
Oh I think you actually just need to load the nvidia compiler
