### ISSUE TITLE
constrain_mask of density and temperature in swiftsimio doesn't work.

### ISSUE THREAD

**Issue by yanlingchen1** [SWIFTSIM/swiftsimio#165]
Hi all,

I wrote a following code and I found out for the `dat` if the temperature and density is not masked, only spatial mask works. And it returned following error. 

Best regards,
Yanling

```The code
import swiftsimio as sw
import numpy as np

# load snapshot data
def WHIM_snapshot_subset():
    # input parameters
    reds = 0.1
    sim = 'L1000N1800'
    snapnum = int(77-reds/0.05)

    filename = f'/cosma8/data/dp004/flamingo/Runs/{sim}/HYDRO_FIDUCIAL/snapshots/flamingo_00{snapnum}/flamingo_00{snapnum}.hdf5'
    mask = sw.mask(filename)
    boxsize = mask.metadata.boxsize
    load_region = [[0.0 * b, 0.001 * b] for b in boxsize]
    mask.constrain_spatial(load_region)

    density_units = mask.units.mass / mask.units.length**3
    temperature_units = mask.units.temperature
    mask.constrain_mask("gas", "density", 100 * density_units, 1e4 * density_units)
    mask.constrain_mask("gas", "temperature", 1e5 * temperature_units, 1e7 * temperature_units)

    data = sw.load(filename, mask=mask)

    return data

dat = WHIM_snapshot_subset()
```

```The error
Traceback (most recent call last):
  File "/cosma8/data/dp004/dc-chen3/work/bin/pixel_spectrum/test/save_single_particle.py", line 24, in <module>
    sw.subset_writer.write_subset("snapshot_subset.hdf5", mask)
  File "/cosma/local/Python/3.10.1/lib/python3.10/site-packages/swiftsimio/subset_writer.py", line 326, in write_subset
    write_datasubset(infile, outfile, mask, find_datasets(infile), list_of_links)
  File "/cosma/local/Python/3.10.1/lib/python3.10/site-packages/swiftsimio/subset_writer.py", line 268, in write_datasubset
    mask_size = get_dataset_mask(mask, name, suffix="_size")
  File "/cosma/local/Python/3.10.1/lib/python3.10/site-packages/swiftsimio/subset_writer.py", line 69, in get_dataset_mask
    part_type = [int(x) for x in filter(str.isdigit, dataset_name)][0]
IndexError: list index out of range
```

**Comment by yanlingchen1** [comment]
Sorry, it is the complete error:
```
[dc-chen3@login8b test]$ python3 save_single_particle.py 
You cannot constrain a mask if spatial_only=True
Please re-initialise the SWIFTMask object with spatial_only=False
You cannot constrain a mask if spatial_only=True
Please re-initialise the SWIFTMask object with spatial_only=False
Traceback (most recent call last):
  File "/cosma8/data/dp004/dc-chen3/work/bin/pixel_spectrum/test/save_single_particle.py", line 27, in <module>
    sw.subset_writer.write_subset("WHIM_snapshot_subset.hdf5", mask)
  File "/cosma/local/Python/3.10.1/lib/python3.10/site-packages/swiftsimio/subset_writer.py", line 326, in write_subset
    write_datasubset(infile, outfile, mask, find_datasets(infile), list_of_links)
  File "/cosma/local/Python/3.10.1/lib/python3.10/site-packages/swiftsimio/subset_writer.py", line 268, in write_datasubset
    mask_size = get_dataset_mask(mask, name, suffix="_size")
  File "/cosma/local/Python/3.10.1/lib/python3.10/site-packages/swiftsimio/subset_writer.py", line 69, in get_dataset_mask
    part_type = [int(x) for x in filter(str.isdigit, dataset_name)][0]
IndexError: list index out of range
```

**Comment by MatthieuSchaller** [comment]
Isn't the error messages telling you what to do:

```
You cannot constrain a mask if spatial_only=True
Please re-initialise the SWIFTMask object with spatial_only=False
```
?

Or am I misunderstanding what the problem is?

**Comment by yanlingchen1** [comment]
Thanks for pointing out! It looks workable if `mask = sw.mask(filename, spatial_only=False)`. But it takes more than 10 mins to do this. So I will still just filter temperatures and densities by my own.
