### ISSUE TITLE
Crash in a SWIFT makeIC script

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/swiftsimio#6]
I am running on cosma7 with the python/3.6.5 module. When running the makeIC.py in the `ConstantCosmoTempEvolution` directory, I get the following error:

```
Traceback (most recent call last):
  File "makeIC.py", line 21, in <module>
    from swiftsimio.units import cosmo_units
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/swiftsimio/units.py", line 15, in <module>
    "cosmological", unyt.Mpc, 1e10 * unyt.msun, unyt.s * unyt.Mpc / unyt.km
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/unyt/unit_systems.py", line 218, in __init__
    bu = _split_prefix(unit, default_lut)[1]
  File "/cosma/home/jlvc76/.local/lib/python3.6/site-packages/unyt/unit_systems.py", line 111, in _split_prefix
    possible_prefix = symbol_str[0]
TypeError: 'Unit' object does not support indexing
```

**Comment by JBorrow** [comment]
I think we resolved this by fixing your unyt version, correct?
